# Generated by Django 5.1.3 on 2024-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_subida',
        ),
        migrations.AddField(
            model_name='imagen',
            name='categoria',
            field=models.CharField(choices=[('camara', 'Cámara'), ('whatsapp', 'WhatsApp'), ('descargas', 'Descargas')], default='camara', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
