# Generated by Django 5.1.3 on 2024-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_imagen_fecha_subida_alter_imagen_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_subida',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='categoria',
            field=models.CharField(choices=[('camara', 'Cámara'), ('descargas', 'Descargas'), ('whatsapp', 'WhatsApp'), ('otros', 'Otros')], max_length=50),
        ),
    ]
