# Generated by Django 5.1.3 on 2024-11-18 23:32
from django.utils.timezone import now
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_rename_titulo_imagen_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=now),
        ),
    ]
