# Generated by Django 5.1.3 on 2024-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_imagen_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
